replicaCount: 1

image:
  repository: ghcr.io/alun-hub/sudo-logserver
  pullPolicy: IfNotPresent
  tag: "1.0"

storage:
  type: local
  local:
    size: 10Gi

tls:
  mode: self-signed
  existingSecret: ""

postgresql:
  enabled: false

minio:
  enabled: false
