apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: sudo-logger
type: Opaque
stringData:
  admin-username: admin
  admin-password: CHANGEME # pragma: allowlist secret
  db-password: CHANGEME # pragma: allowlist secret
