package main

import (
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

var (
	flagServer    = flag.String("server", "localhost:9876", "Log server address (host:port)")
	flagCert      = flag.String("cert", "/etc/sudo-logger/shipper.crt", "Client TLS certificate")
	flagKey       = flag.String("key", "/etc/sudo-logger/shipper.key", "Client TLS private key")
	flagCA        = flag.String("ca", "/etc/sudo-logger/ca.crt", "CA certificate for server verification")
	flagVerifyKey = flag.String("verify-key", "/etc/sudo-logger/ack-verify.pub", "ed25519 public key for ACK verification (optional)")
	flagCgroupRoot = flag.String("cgroup-root", "/sys/fs/cgroup", "Cgroup v2 root path")
	flagHostname  = flag.String("hostname", "", "Override reported hostname (default: os.Hostname)")
)

func main() {
	flag.Parse()

	hostname := resolveHostname()

	tlsCfg, err := buildTLSConfig(*flagCert, *flagKey, *flagCA)
	if err != nil {
		log.Fatalf("TLS config: %v", err)
	}

	var verifyKey []byte
	if *flagVerifyKey != "" {
		verifyKey, err = loadEd25519PubKeyBytes(*flagVerifyKey)
		if err != nil {
			log.Printf("warning: could not load ACK verify key %s: %v (ACKs will not be verified)", *flagVerifyKey, err)
		}
	}

	// Load compiled eBPF objects (generated by bpf2go from bpf/recorder.c).
	objs := recorderObjects{}
	if err := loadRecorderObjects(&objs, nil); err != nil {
		log.Fatalf("load eBPF objects: %v\n(Did you run 'go generate ./cmd/ebpf-recorder/' first?)", err)
	}
	defer objs.Close()

	// Attach to the sys_enter_write tracepoint.
	tp, err := link.Tracepoint("syscalls", "sys_enter_write", objs.RecordWrite, nil)
	if err != nil {
		log.Fatalf("attach tracepoint sys_enter_write: %v", err)
	}
	defer tp.Close()
	log.Println("ebpf-recorder: tracepoint/syscalls/sys_enter_write attached")

	// Start session tracker — watches the cgroup hierarchy for login sessions
	// and manages the tracked_cgroups BPF map.
	tracker := newSessionTracker(
		objs.TrackedCgroups,
		*flagServer,
		tlsCfg,
		verifyKey,
		hostname,
		*flagCgroupRoot,
	)
	go tracker.watch()

	// Read events from the ring buffer and route to the correct session.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("ringbuf reader: %v", err)
	}
	defer rd.Close()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGTERM, syscall.SIGINT)
	go func() {
		<-sigCh
		log.Println("ebpf-recorder: shutting down")
		rd.Close()
	}()

	log.Println("ebpf-recorder: recording all PTY sessions")

	for {
		rec, err := rd.Read()
		if err != nil {
			break
		}
		tracker.handleEvent(rec.RawSample)
	}

	tracker.closeAll()
	log.Println("ebpf-recorder: stopped")
}
