// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadRecorder returns the embedded CollectionSpec for Recorder.
func LoadRecorder() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RecorderBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Recorder: %w", err)
	}

	return spec, err
}

// LoadRecorderObjects loads Recorder and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RecorderObjects
//	*RecorderPrograms
//	*RecorderMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRecorderObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRecorder()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RecorderSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RecorderSpecs struct {
	RecorderProgramSpecs
	RecorderMapSpecs
	RecorderVariableSpecs
}

// RecorderProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RecorderProgramSpecs struct {
	RecordExit  *ebpf.ProgramSpec `ebpf:"record_exit"`
	RecordWrite *ebpf.ProgramSpec `ebpf:"record_write"`
	TraceExecve *ebpf.ProgramSpec `ebpf:"trace_execve"`
}

// RecorderMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RecorderMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	TrackedCgroups  *ebpf.MapSpec `ebpf:"tracked_cgroups"`
	TrackedSudoPids *ebpf.MapSpec `ebpf:"tracked_sudo_pids"`
}

// RecorderVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RecorderVariableSpecs struct {
}

// RecorderObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRecorderObjects or ebpf.CollectionSpec.LoadAndAssign.
type RecorderObjects struct {
	RecorderPrograms
	RecorderMaps
	RecorderVariables
}

func (o *RecorderObjects) Close() error {
	return _RecorderClose(
		&o.RecorderPrograms,
		&o.RecorderMaps,
	)
}

// RecorderMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRecorderObjects or ebpf.CollectionSpec.LoadAndAssign.
type RecorderMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	TrackedCgroups  *ebpf.Map `ebpf:"tracked_cgroups"`
	TrackedSudoPids *ebpf.Map `ebpf:"tracked_sudo_pids"`
}

func (m *RecorderMaps) Close() error {
	return _RecorderClose(
		m.Events,
		m.TrackedCgroups,
		m.TrackedSudoPids,
	)
}

// RecorderVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRecorderObjects or ebpf.CollectionSpec.LoadAndAssign.
type RecorderVariables struct {
}

// RecorderPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRecorderObjects or ebpf.CollectionSpec.LoadAndAssign.
type RecorderPrograms struct {
	RecordExit  *ebpf.Program `ebpf:"record_exit"`
	RecordWrite *ebpf.Program `ebpf:"record_write"`
	TraceExecve *ebpf.Program `ebpf:"trace_execve"`
}

func (p *RecorderPrograms) Close() error {
	return _RecorderClose(
		p.RecordExit,
		p.RecordWrite,
		p.TraceExecve,
	)
}

func _RecorderClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed recorder_bpfeb.o
var _RecorderBytes []byte
