// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SandboxInodeKey struct {
	_   structs.HostLayout
	Ino uint64
	Dev uint32
	Pad uint32
}

// LoadSandbox returns the embedded CollectionSpec for Sandbox.
func LoadSandbox() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SandboxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sandbox: %w", err)
	}

	return spec, err
}

// LoadSandboxObjects loads Sandbox and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SandboxObjects
//	*SandboxPrograms
//	*SandboxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSandboxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSandbox()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SandboxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxSpecs struct {
	SandboxProgramSpecs
	SandboxMapSpecs
	SandboxVariableSpecs
}

// SandboxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxProgramSpecs struct {
	SandboxBpf            *ebpf.ProgramSpec `ebpf:"sandbox_bpf"`
	SandboxFileOpen       *ebpf.ProgramSpec `ebpf:"sandbox_file_open"`
	SandboxFilePermission *ebpf.ProgramSpec `ebpf:"sandbox_file_permission"`
	SandboxInodeCreate    *ebpf.ProgramSpec `ebpf:"sandbox_inode_create"`
	SandboxInodeMkdir     *ebpf.ProgramSpec `ebpf:"sandbox_inode_mkdir"`
	SandboxInodeMknod     *ebpf.ProgramSpec `ebpf:"sandbox_inode_mknod"`
	SandboxInodeRename    *ebpf.ProgramSpec `ebpf:"sandbox_inode_rename"`
	SandboxInodeSetattr   *ebpf.ProgramSpec `ebpf:"sandbox_inode_setattr"`
	SandboxInodeSymlink   *ebpf.ProgramSpec `ebpf:"sandbox_inode_symlink"`
	SandboxInodeUnlink    *ebpf.ProgramSpec `ebpf:"sandbox_inode_unlink"`
	SandboxPathTruncate   *ebpf.ProgramSpec `ebpf:"sandbox_path_truncate"`
	SandboxProcessExit    *ebpf.ProgramSpec `ebpf:"sandbox_process_exit"`
	SandboxProcessFork    *ebpf.ProgramSpec `ebpf:"sandbox_process_fork"`
	SandboxTaskKill       *ebpf.ProgramSpec `ebpf:"sandbox_task_kill"`
}

// SandboxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxMapSpecs struct {
	ProtectedInodes  *ebpf.MapSpec `ebpf:"protected_inodes"`
	ProtectedProcs   *ebpf.MapSpec `ebpf:"protected_procs"`
	SandboxAlerts    *ebpf.MapSpec `ebpf:"sandbox_alerts"`
	SandboxedCgroups *ebpf.MapSpec `ebpf:"sandboxed_cgroups"`
	SandboxedPids    *ebpf.MapSpec `ebpf:"sandboxed_pids"`
}

// SandboxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxVariableSpecs struct {
}

// SandboxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxObjects struct {
	SandboxPrograms
	SandboxMaps
	SandboxVariables
}

func (o *SandboxObjects) Close() error {
	return _SandboxClose(
		&o.SandboxPrograms,
		&o.SandboxMaps,
	)
}

// SandboxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxMaps struct {
	ProtectedInodes  *ebpf.Map `ebpf:"protected_inodes"`
	ProtectedProcs   *ebpf.Map `ebpf:"protected_procs"`
	SandboxAlerts    *ebpf.Map `ebpf:"sandbox_alerts"`
	SandboxedCgroups *ebpf.Map `ebpf:"sandboxed_cgroups"`
	SandboxedPids    *ebpf.Map `ebpf:"sandboxed_pids"`
}

func (m *SandboxMaps) Close() error {
	return _SandboxClose(
		m.ProtectedInodes,
		m.ProtectedProcs,
		m.SandboxAlerts,
		m.SandboxedCgroups,
		m.SandboxedPids,
	)
}

// SandboxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxVariables struct {
}

// SandboxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxPrograms struct {
	SandboxBpf            *ebpf.Program `ebpf:"sandbox_bpf"`
	SandboxFileOpen       *ebpf.Program `ebpf:"sandbox_file_open"`
	SandboxFilePermission *ebpf.Program `ebpf:"sandbox_file_permission"`
	SandboxInodeCreate    *ebpf.Program `ebpf:"sandbox_inode_create"`
	SandboxInodeMkdir     *ebpf.Program `ebpf:"sandbox_inode_mkdir"`
	SandboxInodeMknod     *ebpf.Program `ebpf:"sandbox_inode_mknod"`
	SandboxInodeRename    *ebpf.Program `ebpf:"sandbox_inode_rename"`
	SandboxInodeSetattr   *ebpf.Program `ebpf:"sandbox_inode_setattr"`
	SandboxInodeSymlink   *ebpf.Program `ebpf:"sandbox_inode_symlink"`
	SandboxInodeUnlink    *ebpf.Program `ebpf:"sandbox_inode_unlink"`
	SandboxPathTruncate   *ebpf.Program `ebpf:"sandbox_path_truncate"`
	SandboxProcessExit    *ebpf.Program `ebpf:"sandbox_process_exit"`
	SandboxProcessFork    *ebpf.Program `ebpf:"sandbox_process_fork"`
	SandboxTaskKill       *ebpf.Program `ebpf:"sandbox_task_kill"`
}

func (p *SandboxPrograms) Close() error {
	return _SandboxClose(
		p.SandboxBpf,
		p.SandboxFileOpen,
		p.SandboxFilePermission,
		p.SandboxInodeCreate,
		p.SandboxInodeMkdir,
		p.SandboxInodeMknod,
		p.SandboxInodeRename,
		p.SandboxInodeSetattr,
		p.SandboxInodeSymlink,
		p.SandboxInodeUnlink,
		p.SandboxPathTruncate,
		p.SandboxProcessExit,
		p.SandboxProcessFork,
		p.SandboxTaskKill,
	)
}

func _SandboxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sandbox_bpfel.o
var _SandboxBytes []byte
