// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SandboxInodeKey struct {
	_   structs.HostLayout
	Ino uint64
	Dev uint32
	Pad uint32
}

type SandboxRatelimitKey struct {
	_    structs.HostLayout
	Tgid uint32
	Type uint32
}

// LoadSandbox returns the embedded CollectionSpec for Sandbox.
func LoadSandbox() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SandboxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sandbox: %w", err)
	}

	return spec, err
}

// LoadSandboxObjects loads Sandbox and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SandboxObjects
//	*SandboxPrograms
//	*SandboxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSandboxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSandbox()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SandboxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxSpecs struct {
	SandboxProgramSpecs
	SandboxMapSpecs
	SandboxVariableSpecs
}

// SandboxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxProgramSpecs struct {
	SandboxBpf               *ebpf.ProgramSpec `ebpf:"sandbox_bpf"`
	SandboxBprmCheckSecurity *ebpf.ProgramSpec `ebpf:"sandbox_bprm_check_security"`
	SandboxCapable           *ebpf.ProgramSpec `ebpf:"sandbox_capable"`
	SandboxFileOpen          *ebpf.ProgramSpec `ebpf:"sandbox_file_open"`
	SandboxFilePermission    *ebpf.ProgramSpec `ebpf:"sandbox_file_permission"`
	SandboxInodeCreate       *ebpf.ProgramSpec `ebpf:"sandbox_inode_create"`
	SandboxInodeMkdir        *ebpf.ProgramSpec `ebpf:"sandbox_inode_mkdir"`
	SandboxInodeMknod        *ebpf.ProgramSpec `ebpf:"sandbox_inode_mknod"`
	SandboxInodeRename       *ebpf.ProgramSpec `ebpf:"sandbox_inode_rename"`
	SandboxInodeSetattr      *ebpf.ProgramSpec `ebpf:"sandbox_inode_setattr"`
	SandboxInodeSymlink      *ebpf.ProgramSpec `ebpf:"sandbox_inode_symlink"`
	SandboxInodeUnlink       *ebpf.ProgramSpec `ebpf:"sandbox_inode_unlink"`
	SandboxPathTruncate      *ebpf.ProgramSpec `ebpf:"sandbox_path_truncate"`
	SandboxProcessExit       *ebpf.ProgramSpec `ebpf:"sandbox_process_exit"`
	SandboxProcessFork       *ebpf.ProgramSpec `ebpf:"sandbox_process_fork"`
	SandboxPtraceAccessCheck *ebpf.ProgramSpec `ebpf:"sandbox_ptrace_access_check"`
	SandboxSbMount           *ebpf.ProgramSpec `ebpf:"sandbox_sb_mount"`
	SandboxSocketCreate      *ebpf.ProgramSpec `ebpf:"sandbox_socket_create"`
	SandboxTaskKill          *ebpf.ProgramSpec `ebpf:"sandbox_task_kill"`
	SandboxUnixConnect       *ebpf.ProgramSpec `ebpf:"sandbox_unix_connect"`
}

// SandboxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxMapSpecs struct {
	AlertRatelimit    *ebpf.MapSpec `ebpf:"alert_ratelimit"`
	ForbiddenBinaries *ebpf.MapSpec `ebpf:"forbidden_binaries"`
	NoexecInodes      *ebpf.MapSpec `ebpf:"noexec_inodes"`
	ProtectedInodes   *ebpf.MapSpec `ebpf:"protected_inodes"`
	ProtectedProcs    *ebpf.MapSpec `ebpf:"protected_procs"`
	SandboxAlerts     *ebpf.MapSpec `ebpf:"sandbox_alerts"`
	SandboxConfig     *ebpf.MapSpec `ebpf:"sandbox_config"`
	SandboxedCgroups  *ebpf.MapSpec `ebpf:"sandboxed_cgroups"`
	SandboxedPids     *ebpf.MapSpec `ebpf:"sandboxed_pids"`
	SystemdIpcInodes  *ebpf.MapSpec `ebpf:"systemd_ipc_inodes"`
}

// SandboxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SandboxVariableSpecs struct {
}

// SandboxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxObjects struct {
	SandboxPrograms
	SandboxMaps
	SandboxVariables
}

func (o *SandboxObjects) Close() error {
	return _SandboxClose(
		&o.SandboxPrograms,
		&o.SandboxMaps,
	)
}

// SandboxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxMaps struct {
	AlertRatelimit    *ebpf.Map `ebpf:"alert_ratelimit"`
	ForbiddenBinaries *ebpf.Map `ebpf:"forbidden_binaries"`
	NoexecInodes      *ebpf.Map `ebpf:"noexec_inodes"`
	ProtectedInodes   *ebpf.Map `ebpf:"protected_inodes"`
	ProtectedProcs    *ebpf.Map `ebpf:"protected_procs"`
	SandboxAlerts     *ebpf.Map `ebpf:"sandbox_alerts"`
	SandboxConfig     *ebpf.Map `ebpf:"sandbox_config"`
	SandboxedCgroups  *ebpf.Map `ebpf:"sandboxed_cgroups"`
	SandboxedPids     *ebpf.Map `ebpf:"sandboxed_pids"`
	SystemdIpcInodes  *ebpf.Map `ebpf:"systemd_ipc_inodes"`
}

func (m *SandboxMaps) Close() error {
	return _SandboxClose(
		m.AlertRatelimit,
		m.ForbiddenBinaries,
		m.NoexecInodes,
		m.ProtectedInodes,
		m.ProtectedProcs,
		m.SandboxAlerts,
		m.SandboxConfig,
		m.SandboxedCgroups,
		m.SandboxedPids,
		m.SystemdIpcInodes,
	)
}

// SandboxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxVariables struct {
}

// SandboxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type SandboxPrograms struct {
	SandboxBpf               *ebpf.Program `ebpf:"sandbox_bpf"`
	SandboxBprmCheckSecurity *ebpf.Program `ebpf:"sandbox_bprm_check_security"`
	SandboxCapable           *ebpf.Program `ebpf:"sandbox_capable"`
	SandboxFileOpen          *ebpf.Program `ebpf:"sandbox_file_open"`
	SandboxFilePermission    *ebpf.Program `ebpf:"sandbox_file_permission"`
	SandboxInodeCreate       *ebpf.Program `ebpf:"sandbox_inode_create"`
	SandboxInodeMkdir        *ebpf.Program `ebpf:"sandbox_inode_mkdir"`
	SandboxInodeMknod        *ebpf.Program `ebpf:"sandbox_inode_mknod"`
	SandboxInodeRename       *ebpf.Program `ebpf:"sandbox_inode_rename"`
	SandboxInodeSetattr      *ebpf.Program `ebpf:"sandbox_inode_setattr"`
	SandboxInodeSymlink      *ebpf.Program `ebpf:"sandbox_inode_symlink"`
	SandboxInodeUnlink       *ebpf.Program `ebpf:"sandbox_inode_unlink"`
	SandboxPathTruncate      *ebpf.Program `ebpf:"sandbox_path_truncate"`
	SandboxProcessExit       *ebpf.Program `ebpf:"sandbox_process_exit"`
	SandboxProcessFork       *ebpf.Program `ebpf:"sandbox_process_fork"`
	SandboxPtraceAccessCheck *ebpf.Program `ebpf:"sandbox_ptrace_access_check"`
	SandboxSbMount           *ebpf.Program `ebpf:"sandbox_sb_mount"`
	SandboxSocketCreate      *ebpf.Program `ebpf:"sandbox_socket_create"`
	SandboxTaskKill          *ebpf.Program `ebpf:"sandbox_task_kill"`
	SandboxUnixConnect       *ebpf.Program `ebpf:"sandbox_unix_connect"`
}

func (p *SandboxPrograms) Close() error {
	return _SandboxClose(
		p.SandboxBpf,
		p.SandboxBprmCheckSecurity,
		p.SandboxCapable,
		p.SandboxFileOpen,
		p.SandboxFilePermission,
		p.SandboxInodeCreate,
		p.SandboxInodeMkdir,
		p.SandboxInodeMknod,
		p.SandboxInodeRename,
		p.SandboxInodeSetattr,
		p.SandboxInodeSymlink,
		p.SandboxInodeUnlink,
		p.SandboxPathTruncate,
		p.SandboxProcessExit,
		p.SandboxProcessFork,
		p.SandboxPtraceAccessCheck,
		p.SandboxSbMount,
		p.SandboxSocketCreate,
		p.SandboxTaskKill,
		p.SandboxUnixConnect,
	)
}

func _SandboxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sandbox_bpfeb.o
var _SandboxBytes []byte
