// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTestDpath returns the embedded CollectionSpec for TestDpath.
func LoadTestDpath() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestDpathBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TestDpath: %w", err)
	}

	return spec, err
}

// LoadTestDpathObjects loads TestDpath and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TestDpathObjects
//	*TestDpathPrograms
//	*TestDpathMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTestDpathObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTestDpath()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TestDpathSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestDpathSpecs struct {
	TestDpathProgramSpecs
	TestDpathMapSpecs
	TestDpathVariableSpecs
}

// TestDpathProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestDpathProgramSpecs struct {
	SandboxBprmCheckSecurity *ebpf.ProgramSpec `ebpf:"sandbox_bprm_check_security"`
}

// TestDpathMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestDpathMapSpecs struct {
}

// TestDpathVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestDpathVariableSpecs struct {
}

// TestDpathObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTestDpathObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestDpathObjects struct {
	TestDpathPrograms
	TestDpathMaps
	TestDpathVariables
}

func (o *TestDpathObjects) Close() error {
	return _TestDpathClose(
		&o.TestDpathPrograms,
		&o.TestDpathMaps,
	)
}

// TestDpathMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTestDpathObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestDpathMaps struct {
}

func (m *TestDpathMaps) Close() error {
	return _TestDpathClose()
}

// TestDpathVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTestDpathObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestDpathVariables struct {
}

// TestDpathPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTestDpathObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestDpathPrograms struct {
	SandboxBprmCheckSecurity *ebpf.Program `ebpf:"sandbox_bprm_check_security"`
}

func (p *TestDpathPrograms) Close() error {
	return _TestDpathClose(
		p.SandboxBprmCheckSecurity,
	)
}

func _TestDpathClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed testdpath_bpfel.o
var _TestDpathBytes []byte
