apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudo-logger.fullname" . }}-logserver-admin
  labels:
    {{- include "sudo-logger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9877
      targetPort: 9877
      protocol: TCP
      name: admin
  selector:
    {{- include "sudo-logger.selectorLabels" . | nindent 4 }}
    app: logserver
