apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sudo-logger.fullname" . }}
  labels:
    {{- include "sudo-logger.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.storage.type "local" }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sudo-logger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sudo-logger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: logs
              containerPort: 9876
              protocol: TCP
          args:
            {{- if eq .Values.storage.type "local" }}
            - "-logdir=/var/log/sudoreplay"
            {{- else if eq .Values.storage.type "distributed" }}
            - "-storage=distributed"
            {{- end }}
          volumeMounts:
            - name: logs
              mountPath: /var/log/sudoreplay
            - name: tls
              mountPath: /etc/sudo-logger
      volumes:
        - name: logs
          {{- if eq .Values.storage.type "local" }}
          persistentVolumeClaim:
            claimName: {{ include "sudo-logger.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.existingSecret | default (printf "%s-tls" (include "sudo-logger.fullname" .)) }}
