apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudo-logger.fullname" . }}-logserver
  labels:
    {{- include "sudo-logger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.logserver.service.type }}
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: tls
      {{- if and (eq .Values.logserver.service.type "NodePort") .Values.logserver.service.nodePort }}
      nodePort: {{ .Values.logserver.service.nodePort }}
      {{- end }}
  selector:
    {{- include "sudo-logger.selectorLabels" . | nindent 4 }}
    app: logserver
