{{- if .Values.replay.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudo-logger.fullname" . }}-replay
  labels:
    {{- include "sudo-logger.labels" . | nindent 4 }}
    app.kubernetes.io/component: replay
spec:
  type: {{ .Values.replay.service.type }}
  ports:
    - port: {{ .Values.replay.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "sudo-logger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replay
{{- end }}
