{{- if eq .Values.tls.mode "provided" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sudo-logger.fullname" . }}-tls
  labels:
    {{- include "sudo-logger.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.provided.cert | b64enc }}
  tls.key: {{ .Values.tls.provided.key | b64enc }}
  {{- if .Values.tls.provided.ca }}
  ca.crt: {{ .Values.tls.provided.ca | b64enc }}
  {{- end }}
{{- end }}
