import { useState, type ChangeEvent, type KeyboardEvent } from 'react'
import { BookOpen } from 'lucide-react'
import { InputDialog } from '@/components/ui/confirm-dialog'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { fetchSandbox, saveSandbox, fetchSandboxTemplates, saveSandboxTemplates } from '@/api/config'
import { cn } from '@/lib/utils'

// ── Feature definitions ───────────────────────────────────────────────────────

const FEATURES = [
  { key: 'deny_netlink',           label: 'Block AF_NETLINK',          desc: 'iptables, nftables, ip route, auditctl',           def: true  },
  { key: 'deny_mount',             label: 'Block mount',               desc: 'Prevent bind-mounting over protected paths',        def: true  },
  { key: 'deny_ptrace',            label: 'Block ptrace',              desc: 'Prevent code injection into root daemons',          def: true  },
  { key: 'deny_cap_audit_control', label: 'Block CAP_AUDIT_CONTROL',   desc: 'Defence-in-depth for auditctl',                     def: true  },
  { key: 'deny_cap_net_admin',     label: 'Block CAP_NET_ADMIN',       desc: 'Raw sockets, network admin (may block iproute2)',   def: false },
  { key: 'deny_cap_sys_module',    label: 'Block CAP_SYS_MODULE',      desc: 'Prevent kernel module loading',                     def: true  },
  { key: 'deny_cap_mac_admin',     label: 'Block CAP_MAC_ADMIN',       desc: 'Prevent SELinux policy changes',                    def: true  },
  { key: 'deny_cap_sys_rawio',     label: 'Block CAP_SYS_RAWIO',       desc: '/dev/mem, /dev/port raw I/O access',                def: true  },
  { key: 'deny_cap_sys_boot',      label: 'Block CAP_SYS_BOOT',        desc: 'Prevent kexec_load / reboot from session',          def: true  },
  { key: 'deny_systemd_ipc',       label: 'Restrict Systemd D-Bus IPC', desc: 'Blocks systemctl, loginctl (off by default)',      def: false },
] as const

type FeatureKey = typeof FEATURES[number]['key']
type ProtectKey = 'files' | 'forbidden' | 'noexec' | 'devices' | 'proc' | 'sockets' | 'processes'

interface SandboxState {
  enabled: boolean
  features: Record<FeatureKey, boolean>
  files: string[]
  forbidden: string[]
  noexec: string[]
  devices: string[]
  proc: string[]
  sockets: string[]
  processes: string[]
}

// ── YAML helpers ──────────────────────────────────────────────────────────────

function defaultState(): SandboxState {
  return {
    enabled: true,
    features: Object.fromEntries(FEATURES.map(f => [f.key, f.def])) as Record<FeatureKey, boolean>,
    files: [], forbidden: [], noexec: [], devices: [], proc: [], sockets: [], processes: [],
  }
}

function parseYaml(yaml: string): SandboxState {
  const s = defaultState()
  if (!yaml) return s
  let section: string | null = null
  let currentKey: string | null = null
  for (const rawLine of yaml.split('\n')) {
    const line = rawLine.replace(/#.*/, '').trimEnd()
    if (!line.trim()) continue
    const em = line.match(/^enabled:\s*(true|false)/)
    if (em) { s.enabled = em[1] === 'true'; continue }
    if (/^features:/.test(line)) { section = 'features'; currentKey = null; continue }
    if (/^protect:/.test(line))  { section = 'protect';  currentKey = null; continue }
    if (section === 'features') {
      const m = line.match(/^ {2}(deny_\w+):\s*(true|false)/)
      if (m) (s.features as any)[m[1]] = m[2] === 'true'
    } else if (section === 'protect') {
      const km = line.match(/^ {2}(files|forbidden|noexec|devices|proc|sockets|processes):/)
      if (km) { currentKey = km[1]; continue }
      const im = line.match(/^ {4}- (.+)/)
      if (im && currentKey) {
        let v = im[1].trim()
        if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1)
        ;(s as any)[currentKey].push(v)
      }
    }
  }
  return s
}

function buildYaml(s: SandboxState): string {
  let yaml = '# /etc/sudo-logger/sandbox.yaml\n# Generated by replay-server UI\n\n'
  if (!s.enabled) yaml += 'enabled: false\n\n'
  yaml += 'features:\n'
  for (const f of FEATURES) yaml += `  ${f.key}: ${s.features[f.key]}\n`
  yaml += '\nprotect:\n'
  const keys: ProtectKey[] = ['files', 'forbidden', 'noexec', 'devices', 'proc', 'sockets', 'processes']
  for (const k of keys) {
    const list = s[k]
    if (list.length) { yaml += `  ${k}:\n`; list.forEach(v => { yaml += `    - ${v}\n` }) }
  }
  return yaml
}

const BUILTIN_YAML = `features:
  deny_netlink: true
  deny_mount: true
  deny_ptrace: true
  deny_cap_audit_control: true
  deny_cap_net_admin: false
  deny_cap_sys_module: true
  deny_cap_mac_admin: true
  deny_cap_sys_rawio: true
  deny_cap_sys_boot: true
  deny_systemd_ipc: false

protect:
  files:
    - /etc/sudo
    - /etc/sudoers
    - /etc/sudoers.d
    - /etc/sudo-logger
    - /etc/pam.d
    - /etc/security
    - /etc/audit/audit.rules
    - /etc/audit/rules.d
    - /etc/rsyslog.conf
    - /etc/rsyslog.d
    - /etc/systemd
    - /usr/lib/systemd
    - /root/.ssh
    - /root/.ssh/authorized_keys
    - /etc/pki
    - /etc/crypto-policies
  forbidden:
    - /usr/bin/systemd-run
    - /usr/bin/busctl
    - /usr/bin/machinectl
    - /usr/bin/firewall-cmd
    - /usr/sbin/nft
    - /usr/sbin/iptables
    - /usr/sbin/ip6tables
    - /usr/sbin/auditctl
    - /usr/sbin/setenforce
    - /usr/sbin/semodule
    - /usr/sbin/kexec
  noexec:
    - /tmp
    - /var/tmp
    - /dev/shm
    - /run/user
  devices:
    - /dev/mem
    - /dev/kmem
    - /dev/port
    - /dev/sda
    - /dev/sdb
    - /dev/nvme0n1
  proc:
    - /proc/sysrq-trigger
    - /proc/kcore
    - /proc/kallsyms
    - /proc/sys/kernel/core_pattern
    - /proc/sys/kernel/modules_disabled
  sockets:
    - /run/sudo-logger/plugin.sock
    - /run/systemd/journal/socket
    - /run/systemd/journal/stdout
  processes:
    - auditd
    - rsyslogd
    - syslog-ng
    - systemd-journal
    - sshd
    - sudo-logger-age
`

// ── Tag input ─────────────────────────────────────────────────────────────────

function TagInput({ label, values, onChange }: { label: string; values: string[]; onChange: (v: string[]) => void }) {
  const [draft, setDraft] = useState('')
  const add = () => {
    const v = draft.trim()
    if (v && !values.includes(v)) onChange([...values, v])
    setDraft('')
  }
  return (
    <div className="space-y-1.5">
      <label className="text-[10px] font-bold text-text-dim uppercase tracking-wider">{label}</label>
      <div className="flex gap-1">
        <input
          value={draft}
          onChange={(e: ChangeEvent<HTMLInputElement>) => setDraft(e.target.value)}
          onKeyDown={(e: KeyboardEvent<HTMLInputElement>) => {
            if (e.key === 'Enter' || e.key === ',') { e.preventDefault(); add() }
          }}
          placeholder="type and press Enter…"
          className="flex-1 h-7 bg-card border border-border rounded-[4px] px-2 text-[12px] outline-none focus:border-green text-text-sub font-mono"
        />
        <button
          onClick={add}
          className="h-7 px-2 bg-card border border-border rounded-[4px] text-[11px] text-text-dim hover:border-border-mid hover:text-text transition-colors"
        >Add</button>
      </div>
      {values.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {values.map(v => (
            <span key={v} className="flex items-center gap-1 bg-card border border-border rounded-[3px] text-[11px] px-2 py-0.5 font-mono text-text-sub">
              {v}
              <button onClick={() => onChange(values.filter(x => x !== v))} className="text-text-dim hover:text-red ml-0.5">×</button>
            </span>
          ))}
        </div>
      )}
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

export function SandboxTab() {
  const qc = useQueryClient()
  const { data: raw, isPending, isError } = useQuery({ queryKey: ['sandbox'], queryFn: fetchSandbox })
  const { data: templates = {} } = useQuery({ queryKey: ['sandbox-templates'], queryFn: fetchSandboxTemplates })

  const [state, setState] = useState<SandboxState | null>(null)
  const [status, setStatus] = useState<{ msg: string; err: boolean } | null>(null)
  const [templateSel, setTemplateSel] = useState('')
  const [tmplNameOpen, setTmplNameOpen] = useState(false)

  const current: SandboxState = state ?? (raw ? parseYaml(raw.content) : defaultState())

  const showStatus = (msg: string, err = false) => {
    setStatus({ msg, err })
    setTimeout(() => setStatus(null), 5000)
  }

  const save = useMutation({
    mutationFn: () => saveSandbox(buildYaml(current)),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['sandbox'] }); setState(null); showStatus('Saved — agents will reload within 60 s') },
    onError: (e: any) => showStatus('Save failed: ' + e.message, true),
  })

  const saveTmpl = useMutation({
    mutationFn: async (name: string) => {
      const next = { ...templates, [name]: buildYaml(current) }
      await saveSandboxTemplates(next)
      return name
    },
    onSuccess: (name: string) => { qc.invalidateQueries({ queryKey: ['sandbox-templates'] }); showStatus(`Template "${name}" saved`) },
    onError: (e: any) => showStatus('Save template failed: ' + e.message, true),
  })

  const loadTemplate = () => {
    if (!templateSel) return
    let yaml = ''
    if (templateSel === 'builtin:hardening') yaml = BUILTIN_YAML
    else if (templateSel.startsWith('custom:')) yaml = templates[templateSel.slice(7)]
    if (yaml) { setState(parseYaml(yaml)); showStatus('Template loaded') }
  }

  const setEnabled = (val: boolean) => setState({ ...current, enabled: val })

  const setFeature = (key: FeatureKey, val: boolean) =>
    setState({ ...current, features: { ...current.features, [key]: val } })

  const setList = (key: ProtectKey, val: string[]) =>
    setState({ ...current, [key]: val })

  if (isPending) return <div className="p-6 text-text-dim font-mono text-[13px]">Loading sandbox config…</div>
  if (isError)   return <div className="p-6 text-red font-mono text-[13px]">Failed to load sandbox config</div>

  const isDirty = state !== null

  return (
    <div className="p-6 space-y-6 max-w-6xl animate-in fade-in duration-200">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border pb-3">
        <div>
          <h2 className="text-[15px] font-semibold text-text">Process Sandbox</h2>
          <p className="text-[12px] text-text-dim mt-0.5">
            {raw?.path && <span className="font-mono text-text-dim">{raw.path}</span>}
          </p>
        </div>
        <div className="flex items-center gap-3">
          {status && (
            <span className={cn('text-[12px] font-mono', status.err ? 'text-red' : 'text-green')}>
              {status.msg}
            </span>
          )}
          <a
            href="/docs/manual.html#yaml-sandbox"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-[12px] text-text-dim hover:text-green transition-colors"
          >
            <BookOpen size={13} /> Docs
          </a>
          <button
            onClick={() => setEnabled(!current.enabled)}
            className={cn(
              'h-8 px-3 rounded-[4px] text-[12px] font-bold border transition-colors',
              current.enabled
                ? 'bg-green-dim border-green text-green hover:bg-green/20'
                : 'bg-red/10 border-red/50 text-red hover:bg-red/20'
            )}
          >{current.enabled ? 'Enabled' : 'Disabled'}</button>
          <button
            onClick={() => setTmplNameOpen(true)}
            className="h-8 px-3 bg-card border border-border rounded-[4px] text-[12px] text-text-dim hover:border-border-mid hover:text-text transition-colors"
          >Save as template</button>
          <button
            onClick={() => save.mutate()}
            disabled={save.isPending}
            className={cn(
              'h-8 px-5 rounded-[4px] text-[13px] font-bold transition-colors',
              isDirty
                ? 'bg-green text-black hover:bg-green/90'
                : 'bg-green/30 text-green/60 cursor-not-allowed'
            )}
          >{save.isPending ? 'Saving…' : 'Save sandbox.yaml'}</button>
        </div>
      </div>

      {/* Disabled banner */}
      {!current.enabled && (
        <div className="flex items-center gap-3 px-4 py-3 bg-red/10 border border-red/30 rounded-[5px] text-[12px] text-red">
          <span className="font-bold shrink-0">Sandbox disabled.</span>
          <span className="text-red/70">eBPF enforcement is off — no filesystem or process restrictions are active. Save to push this state to all agents within 60 s.</span>
        </div>
      )}

      {/* Template loader */}
      <div className={cn('flex items-center gap-2 p-3 bg-card border border-border rounded-[5px]', !current.enabled && 'opacity-40 pointer-events-none')}>
        <span className="text-[12px] text-text-dim shrink-0">Load template:</span>
        <select
          value={templateSel}
          onChange={e => setTemplateSel(e.target.value)}
          className="flex-1 h-8 bg-surface border border-border rounded-[4px] px-2 text-[12px] text-text-sub outline-none focus:border-green"
        >
          <option value="">-- Select template --</option>
          <option value="builtin:hardening">Default Hardening (Fedora/RHEL)</option>
          {Object.keys(templates).sort().map(name => (
            <option key={name} value={`custom:${name}`}>{name}</option>
          ))}
        </select>
        <button
          onClick={loadTemplate}
          disabled={!templateSel}
          className="h-8 px-4 bg-card border border-border rounded-[4px] text-[12px] text-text-dim hover:border-border-mid hover:text-text transition-colors disabled:opacity-40"
        >Load</button>
      </div>

      <div className={cn('grid grid-cols-1 xl:grid-cols-2 gap-8', !current.enabled && 'opacity-40 pointer-events-none')}>
        {/* Left: Features + protect lists */}
        <div className="space-y-6">
          {/* Feature flags */}
          <div className="space-y-2">
            <h3 className="text-[11px] font-bold text-text-dim uppercase tracking-widest">Security Features (BPF)</h3>
            <div className="bg-card border border-border rounded-[5px] divide-y divide-border">
              {FEATURES.map(f => (
                <label key={f.key} className="flex items-center gap-3 px-4 py-2.5 cursor-pointer hover:bg-card-hover transition-colors">
                  <input
                    type="checkbox"
                    checked={current.features[f.key]}
                    onChange={e => setFeature(f.key, e.target.checked)}
                    className="w-4 h-4 accent-green cursor-pointer shrink-0"
                  />
                  <div className="flex-1 min-w-0">
                    <div className="text-[13px] font-medium text-text">{f.label}</div>
                    <div className="text-[11px] text-text-dim">{f.desc}</div>
                  </div>
                  <span className={cn('text-[10px] font-bold uppercase px-1.5 py-0.5 rounded-[3px] shrink-0',
                    current.features[f.key]
                      ? 'bg-green-dim text-green'
                      : 'bg-card border border-border text-text-dim'
                  )}>
                    {current.features[f.key] ? 'ON' : 'OFF'}
                  </span>
                </label>
              ))}
            </div>
          </div>
        </div>

        {/* Right: Protect lists */}
        <div className="space-y-5">
          <h3 className="text-[11px] font-bold text-text-dim uppercase tracking-widest">Protected Resources</h3>
          <TagInput label="Protected Files / Dirs"   values={current.files}     onChange={v => setList('files', v)} />
          <TagInput label="Forbidden Executables"     values={current.forbidden} onChange={v => setList('forbidden', v)} />
          <TagInput label="No-exec Directories"       values={current.noexec}    onChange={v => setList('noexec', v)} />
          <TagInput label="Devices"                   values={current.devices}   onChange={v => setList('devices', v)} />
          <TagInput label="Protected /proc Entries"   values={current.proc}      onChange={v => setList('proc', v)} />
          <TagInput label="Sockets"                   values={current.sockets}   onChange={v => setList('sockets', v)} />
          <TagInput label="Protected Processes (comm)" values={current.processes} onChange={v => setList('processes', v)} />
          <p className="text-[11px] text-text-dim italic">
            Saved changes are fetched by all agents within 60 seconds — no agent restart needed.
          </p>
        </div>
      </div>
      <InputDialog
        open={tmplNameOpen}
        title="Save as Template"
        message="Enter a name for this template:"
        placeholder="my-hardened-config"
        confirmLabel="Save"
        onConfirm={name => { saveTmpl.mutate(name); setTmplNameOpen(false) }}
        onCancel={() => setTmplNameOpen(false)}
      />
    </div>
  )
}
